
version: '3.8'
services:
  gnps_ml_processing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gnps_ml_processing
    volumes:
      - ./GNPS_ML_Processing:/GNPS_ML_Processing
    # volumes:
    #   - type: bind
    #     source: ./GNPS_ML_Processing
    #     target: /GNPS_ML_Processing
    ports:
    - "9000:9000"
    restart: unless-stopped
    command: nextflow run nf_workflow.nf -resume