-include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=networking_barebone
TOOL_FOLDER_NAME=networking_barebone
WORKFLOW_VERSION=release_30
WORKFLOW_DESCRIPTION="Networking Barebones"
