name: gnps_ml_processing_env2
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.8.8
  - numpy=1.24.4
  - pandas=2.0.3
  - tqdm=4.66.1
  - joblib=1.3.2
  - pyarrow=10.0.1
  - fastparquet=2023.8.0
  - pyteomics=4.6.2 
  - networkx=3.1 
  - requests=2.31.0
  - beautifulsoup4=4.12.2
  - lxml=4.8.0
  - pip
  - pip:
    - obonet=1.0.0
    - vaex=4.17.0 
    - pandarallel=1.6.5 
    - dask=2023.5.0
    - rdkit=2023.3.3
    #- pandarallel
  # - pyteomics
  # - tqdm
  # - rdkit
  # - joblib
  # - pyarrow
  