name: gnps_ml_processing_env2
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.8.8
  - pandas
  - requests
  - beautifulsoup4
  - networkx
  - numpy
  - lxml
  - pip
  - pip:
    - obonet

    #- pandarallel
  # - pyteomics
  # - tqdm
  # - rdkit
  # - joblib
  # - pyarrow
  