name: gnps_ml_processing_env2
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.8.8
  - numpy
  - pandas
  - tqdm
  - joblib
  - pyarrow
  - fastparquet
  - pyteomics
  - networkx
  - requests
  - beautifulsoup4
  - networkx
  - lxml
  - pip
  - pip:
    - obonet
    - vaex
    - pandarallel 
    - dask
    - rdkit
    #- pandarallel
  # - pyteomics
  # - tqdm
  # - rdkit
  # - joblib
  # - pyarrow
  