name: splitting_env
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.8.8
  - snappy<1.2 # 1.2.0 is a broken build.
  - pydantic<=1.10.8 # Later versions break vaex
  - pip
  - pytest
  - numpy
  - pandas
  - pyteomics
  - tqdm
  - expiringdict
  - rdkit
  - joblib
  - rdkit
  - pandarallel
  - vaex
  - pip
  - pip:
    - matchms