run_test:
	nextflow run workflow.nf -resume -c nextflow.config

run_test_blink:
	nextflow run workflow.nf -resume --similarity="blink" -c nextflow.config

run_test_simile:
	nextflow run workflow.nf -resume --similarity="simile" -c nextflow.config

run_test_entropy:
	nextflow run workflow.nf -resume --similarity="entropy" -c nextflow.config